# Generated by Django 5.2.6 on 2025-09-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_extractedepub'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedEpub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(default='auto', max_length=10)),
                ('target_lang', models.CharField(default='pt', max_length=10)),
                ('translated_title', models.CharField(blank=True, max_length=255)),
                ('translated_metadata', models.JSONField(blank=True, null=True)),
                ('translated_chapters', models.JSONField(blank=True, null=True)),
                ('chapter_index', models.IntegerField(blank=True, null=True)),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='uploads.extractedepub')),
            ],
            options={
                'unique_together': {('extracted_epub', 'source_lang', 'target_lang', 'chapter_index')},
            },
        ),
    ]
