# Generated by Django 5.2.6 on 2025-09-12 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_translatedepub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'File Upload'), ('extract', 'Content Extraction'), ('translate', 'Translation'), ('download', 'File Download'), ('delete', 'File Deletion'), ('login', 'User Login'), ('register', 'User Registration')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='uploads_aud_user_id_9d8dd7_idx'), models.Index(fields=['timestamp'], name='uploads_aud_timesta_709cc9_idx')],
            },
        ),
    ]
