# Generated by Django 4.2.7 on 2025-09-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'File Upload'), ('extract', 'Content Extraction'), ('translate', 'Translation'), ('download', 'File Download'), ('delete', 'File Deletion'), ('login', 'User Login'), ('register', 'User Registration'), ('read', 'Reading Progress')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.IntegerField(default=0)),
                ('current_position', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_epub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.extractedepub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'extracted_epub'], name='uploads_rea_user_id_22f497_idx'), models.Index(fields=['last_read_at'], name='uploads_rea_last_re_f7ee33_idx')],
                'unique_together': {('user', 'extracted_epub')},
            },
        ),
    ]
