# Generated by Django 4.2.7 on 2025-09-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_alter_auditlog_action_readingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedepub',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
