# Generated by Django 4.2.7 on 2025-09-18 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0006_extractedepub_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=2)),
                ('font_size', models.IntegerField(default=16)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('font_family', models.CharField(default='serif', max_length=30)),
                ('line_height', models.FloatField(default=1.7)),
                ('page_width', models.CharField(default='medium', max_length=10)),
                ('text_align', models.CharField(default='left', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='uploads_rea_updated_23719d_idx')],
            },
        ),
    ]
