# Generated by Django 4.2.7 on 2025-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_readerpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='debug_id',
            field=models.CharField(blank=True, help_text='Debug identifier for tracking imports', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'File Upload'), ('extract', 'Content Extraction'), ('translate', 'Translation'), ('download', 'File Download'), ('delete', 'File Deletion'), ('login', 'User Login'), ('register', 'User Registration'), ('read', 'Reading Progress'), ('ao3_import', 'AO3 Import')], max_length=20),
        ),
    ]
